name: Release PDF

on:
  pull_request:
    branches: [main]
    paths: 'resume/README.md'
    types: [closed]

jobs:
  release:
    name: Release PDF
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm install
      - name: Build PDF
        run: npm run build:pdf
      ################ Create Tag & Release ################
      - name: Create Tag
        id: create-tag
        if: github.event.pull_request.merged
        run: |
          PR_NUM=${{ github.event.number }}
          PR_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/pull/${PR_NUM}"
          TAG_NAME="release/${PR_NUM}-${GITHUB_SHA::7}"
          PUSH_URL="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}"
          git tag ${TAG_NAME}
          git push ${PUSH_URL} ${TAG_NAME}
          echo "::set-output name=tag-name::${TAG_NAME}"
          echo "::set-output name=pr-num::${PR_NUM}"
          echo "::set-output name=pr-url::${PR_URL}"
      - name: Create Release
        id: create-release
        uses: softprops/action-gh-release@v1
        if: github.event.pull_request.merged
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create-tag.outputs.tag-name }}
          name: "Release #${{ steps.create-tag.outputs.pr-num }}"
          body: ${{ steps.create-tag.outputs.pr-url }}
          draft: true
      - name: upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        if: github.event.pull_request.merged
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./resume/README.pdf
          asset_name: resume.pdf
          asset_content_type: application/pdf